spring.application.name=esports-tournaments

#Conexión a PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/esports_db
spring.datasource.username=postgres
spring.datasource.password=trebujena9706

#Configuracion de JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format-sql=true
spring.jpa.open-in-view=false
